baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Andrea Bellucci blog'

[params.author]
  name = 'Andrea Bellucci'

[module]
    [[module.imports]]
        path = 'github.com/hugo-sid/hugo-blog-awesome'

[menu]
    [[menu.main]]
        identifier = 'home'
        name = 'Home'
        url = '/'
        weight = 1

    [[menu.main]]
        identifier = 'posts'
        name = 'Posts'
        url = '/posts/'
        weight = 2

[[params.socialIcons]]
    name = 'github'
    url = 'https://github.com/abellucci93'
